ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
	[0xff, 0x00, 0xf8, 0xff]
]

version = 17

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10
"4" = 20
"5" = 40

# [[structure]]
# name = "old-stuff"
# file = "images/everything.png"
# startx = 1333
# starty = 753
# riority = 0

# [[structure]]
# name = "rwth2"
# file = "images/rwth+fh-big.png"
# startx = 1332
# starty = 1172
# priority = 0

# [[structure]]
# name = "hwst"
# file = "images/hswt.png"
# startx = 1235
# starty = 1201
# priority = 0

#[[structure]]
#name = "fish-background"
#file = "images/fish-background.png"
#startx = 1333
#starty = 753
#priority = 0

# [[structure]]
# name = "augsburg"
# file = "images/augsburg.png"
# startx = 1370
# starty = 1400
# priority = 4

# [[structure]]
# name = "slime"
# file = "images/slime.png"
# startx = 1332
# starty = 753
# priority = 0

[[structure]]
name = "logo2"
file = "images/logo_new_canvas.png"
startx = 1238
starty = 1177
priority = 5

# [[structure]]
# name = "lmu"
# file = "images/lmao.png"
# startx = 1241
# starty = 1191
# priority = 1

[[structure]]
name = "fish2"
file = "images/pleadfish.png"
startx = 1217
starty = 1173
priority = 3

[[structure]]
name = "small_tum_tuw"
file = "images/tum_tuw_small.png"
startx = 1232
starty = 1173
priority = 3

[[structure]]
name = "augsburg2"
file = "images/augsburg2.png"
startx = 1304
starty = 1948
priority = 2